---
hadoop_cluster_name: mycluster
hadoop_reformat_namenode: False

# Shared Edits Dir is needed for HA if multiple NameNodes are specified, so use only if more than one NameNode is specified
# This directory must be a shared directory and accessible from all the NameNodes 
# (e.g. you have to set up a NFS share and mount it on all the NameNodes)
#hadoop_hdfs_site: {"dfs.namenode.shared.edits.dir": "/mnt/gpfs0/hdfs-ha"}
