---
- name: Set up KVM platform
  include_tasks: "{{ item }}"
  loop:
    - install.yml
    - network.yml

- name: Configure Virtual Machines
  include_tasks: vm.yml
  loop: "{{ virtual_machines }}"
  loop_control:
    loop_var: vm
