---
- name: configure template files
  delegate_to: localhost
  template:
    src: ./templates/{{ item }}.j2
    dest: "../../files/hadoop/{{ item }}"
    owner: hdfs
    group: hadoop
  loop:
    - core-site.xml
    - hdfs-site.xml
    - yarn-site.xml
    - mapred-site.xml
  tags: configureHadoopConfig

- name: configure config files
  copy:
    content: "{{ lookup('file', '../../files/hadoop/' + item) }}"
    dest: "{{ hadoop_distro_home }}/etc/hadoop/{{ item }}"
    owner: hdfs
    group: hadoop
  loop:
    - core-site.xml
    - hdfs-site.xml
    - yarn-site.xml
    - mapred-site.xml
  tags: configureHadoopConfig
