---
- name: set hadoop package name from URL
  set_fact: hadoop_distro_pkg_name={{ hadoop_distro_url.split('/')[-1] }}

- name: download hadoop distro    
  get_url:
    url: "{{ hadoop_distro_url }}"
    dest: "{{ hadoop_target_dir }}/{{ hadoop_distro_pkg_name }}"
  tags: hadoop, installHadoop

- name: unpack hadoop distro
  unarchive:
    src: "{{ hadoop_target_dir }}/{{ hadoop_distro_pkg_name }}"
    dest: "{{ hadoop_target_dir }}"
    list_files: yes
    remote_src: yes
  register: archive_contents
  tags: hadoop, installHadoop

- name: create link to current hadoop distro
  file:
    path: "{{ hadoop_distro_home }}"
    src: "{{ archive_contents.files[0] }}"
    state: link
  tags: hadoop, installHadoop