- name: create JRE target directory
  file:
    path: "{{ jre_target_dir }}"
    state: directory
  tags: jre

- name: set JRE package name from URL
  set_fact: jre_pkg_name={{ jre_url.split('/')[-1] }}

- name: download JRE
  get_url: 
    url: "{{ jre_url }}"
    dest: "{{ jre_target_dir }}/{{ jre_pkg_name }}"
  tags: jre
 
- name: unpack JRE
  unarchive:
    src: "{{ jre_target_dir }}/{{ jre_url.split('/')[-1] }}"
    dest: "{{ jre_target_dir }}"
    remote_src: yes
    list_files: yes
  register: archive_contents
  tags: jre

- name: create link to jre
  file:
    path: "{{ jre_target_dir }}/current"
    src: "{{ archive_contents.files[0] }}"
    state: link
  tags: jre
  